# Generated by Django 3.1.3 on 2020-11-15 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodBookApp', '0005_auto_20201115_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(default='deafult.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(default='User has not entered a Bio', max_length=200)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_profile', to='foodBookApp.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
