# Generated by Django 3.1.3 on 2020-11-15 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodBookApp', '0009_auto_20201115_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
