# Generated by Django 3.1.3 on 2020-11-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBookApp', '0011_auto_20201115_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='User has not entered a Bio', max_length=200),
        ),
    ]
