# Generated by Django 3.1.3 on 2020-11-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodBookApp', '0016_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodBookApp.profile'),
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
