# Generated by Django 3.1.3 on 2020-11-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBookApp', '0021_auto_20201117_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='Public', max_length=7),
        ),
    ]
