# Generated by Django 3.1.3 on 2020-11-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodBookApp', '0022_profile_privacy'),
        ('foodBookApp', '0025_post_total_comments'),
    ]

    operations = [
    ]
